#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains custom header

sudo apt-get -y update
sudo apt-get -y install nginx

# Custom index page
echo "ALX Software Engineering!" > /var/www/html/chela.html

# Custom 404 page
echo "Page not found" | sudo tee /var/www/html/404.html > /dev/null

# Modify the `default` file to add your server block configuration
sudo bash -c 'cat <<EOL > /etc/nginx/sites-enabled/default
server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index chela.html index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/Chelagat-Pauline-Gechure;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}
EOL'

# Code for http_response_header.
if ! grep -q 'add_header X-Served-By \$hostname;' /etc/nginx/nginx.conf; then
    sudo sed -i '/^http {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
fi

sudo service nginx restart
