#!/usr/bin/env bash
# Modify `default` config file of an Nginx server to listen on port 80

# Remove buggy default file
rm /etc/nginx/sites-enabled/default

# Symbolic link to the correct default file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
