#!/usr/bin/env bash
# The script that displays the content of the file /etc/passwd.
# Displays username, user id, home directory path for the user.
while read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
