#!/usr/bin/env bash
# This script is modifying hosts.
# localhost resolves to 127.0.0.2
# facebook resolves to 8.8.8.8

cp /etc/hosts ~/temp
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/'  ~/temp
cp -f ~/temp /etc/hosts
